### PR TITLE
Leverage registry to download IdP's metadata

### PR DESCRIPTION
**Pull request by francescm**
Reference registry metadata service from agid that is more convenient than fetching (and keeping updated!) all of IdP's metadata from their own download site.

### CODE REVIEW

**Comment by peppelinux** [comment]
Ok @francescm, nice one!

I asked a revision to @robertogallea and then I'd like to have a new release of this SDK if you agree, so condider to prupose a new MAJOR version  

I think that this SDK is more than a 0.4.things

**Comment by peppelinux** [comment]
Do we solved some of these issues as well?
https://github.com/italia/spid-sp-shibboleth/issues

**Comment by robertogallea** [comment]
It seems just fine to me, thanks @francescm!

**Comment by francescm** [comment]
> Do we solved some of these issues as well? https://github.com/italia/spid-sp-shibboleth/issues

imho to address those issues the cineca's stategy is the most promising: it is maybe a façade job, but it solves them all.

**Pull request merged**
